#!/bin/bash

if [ -z "$NO_COLOR"]; then
readonly RED="\033[1;31m"
readonly GREEN="\033[1;32m"
readonly BLUE="\033[1;34m"
readonly YELLOW="\033[1;33m"
readonly DRED="\033[0;31m"
readonly DGREEN="\033[0;32m"
readonly DBLUE="\033[0;34m"
readonly DYELLOW="\033[0;33m"
readonly RESET="\033[0m"
fi

if [ $UID -ne 0 ]; then
               echo -e  "$REDPlease run this as root. We need to chroot.$RESET"
fi
	
echo -e"$DRED   ############   ####     ###########   ###########        "          
echo -e "$RED  #...........#@ #...#@   #..........#@ #..........#@        "         
echo -e "$GREEN  #\"\"##########@ #\"\"\"#@   #\"\"######\"\"#@ #\"\"######\"\"#@       "          
echo -e "$DGREEN  #\"\"#@@@@@@@@@@ #;;;#@   #;;#    #;;#@ #;;#    #;;#@       "          
echo -e "$YELLOW  #;;#@          #;;;#@   #;;#    #;;#@ #;;#    #;;#@        "         
echo -e "$DYELLOW  #;;#@          #;;;#@   #;;#    #;;#@ #;;#    #;;#@        "         
echo -e "$DRED  #;;##########  #;;;#@   #;;#    #;;#@ #;;#    #;;#@            "     
echo -e "$RED  #==========#@  #===#@   #==#    #==#@ #==#    #==#@              "    
echo -e "$BLUE          #==#@  #===#@   #==#    #==#@ #==#    #==#@              "   
echo -e "$DYELLOW          #==#@  #===#@   #==#    #==#@ #==#    #==#@            "     
echo -e "$YELLOW          #==#@  #%%%#@   #==#    #==#@ #==#    #==#@              "   
echo -e "$GREEN  #########==#@  #%%%#@   #%%#    #%%#@ #%%#    #%%#@                " 
echo -e "$DGREEN  #%%%%%%%%%%#@  #%%%#@   #%%#    #%%#@ #%%#    #%%#@                " 
echo -e "$DBLUE  #&&&&&&&&&&#@  #&&&#@   #&&#    #&&#@ #&&#    #&&#@                 "
echo -e "$DYELLOW  #XXXXXXXXXX#@  #XXX#@   #XXXXXXXXXX#@ #XXXXXXXXXX#@                " 
echo -e "$DRED  ############@  #####@   ############@ ############@                 "
echo -e "$RED   @@@@@@@@@@@@   @@@@@    @@@@@@@@@@@@  @@@@@@@@@@@@      $RESET"

echo "$DGREENSetting open files limits higher...$RESET"
ulimit -n 65535

if ! [ "$1" = "noclean" ] && ! [ -d ./cache ]; then
rm -rf ./cache
else
mv ./cache ./cache.bak &> /dev/null
fi

umount -l ./chroot/dev &> /dev/null
umount -l ./chroot/dev/pts &> /dev/null
umount -l ./chroot/* &> /dev/null

rm -rf ./chroot
rm -rf ./.build
echo '' > build.log

if [ -d config ]; then
    cd config
    rmdir * &> /dev/null
    rm * &> /dev/null
    cd ..
fi

lb clean
lb init --distribution sid --project debian
lb config --architecture amd64 --distribution sid --archive-areas "main contrib non-free" --mirror-binary "http://ftp.debian.org/debian/" --mirror-bootstrap "http://ftp.debian.org/debian/" --iso-application "s100" --iso-preparer "s100" --iso-publisher "s100" --iso-volume "s100"
if [ "$1" = "noclean" ] && [ -d ./cache.bak ]; then
	mv ./cache.bak ./cache
fi
lb build | tee build.log
