#!/bin/sh

read -p "This script may need to install packages from the main debian repos to build S100. No repos will be added. Packages are git, live-build, dialog, debootstrap and their dependencies. Press Ctrl-C to terminate, press enter to continue." REPLY
if [ -n `which git` ]]; then
	apt-get install git
fi
if [ -n `which lb` ]; then
	apt-get install live-build debootstrap
fi

if [ -n `which dialog` ];then
	apt-get install dialog
fi

if [ $UID -ne 0 ]; then
        echo "Please run this as root. We need to chroot."
fi
	
echo "###############################"
echo "## Starting S100 Build...    ##"
echo "##                           ##"
echo "## logging to ./build.log    ##"
echo "###############################"
echo "Setting open files limits higher..."
ulimit -n65535

mv cache cache.bak
rm -rf ./chroot
rm -rf ./.build
lb clean
mv cache.bak cache
	lb config --architecture i386 --distribution sid --linux-flavours 686-pae --archive-areas "main contrib non-free" --mirror-binary "http://ftp.debian.org/debian/" --mirror-bootstrap "http://ftp.debian.org/debian/" --iso-application "s100" --iso-preparer "s100" --iso-publisher "s100" --iso-volume "s100"
lb build | tee build.log

exit 0
