#!/bin/bash
#
# randomize network MAC addresses

### BEGIN INIT INFO
# Provides:          randmac
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S 2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MAC Randomization
# Description:       This init script randomizes the MAC address of all the NICs it can
### END INIT INFO

NICS=$(/sbin/ifconfig -a | /usr/bin/awk '/Link encap:Ethernet/{print $1}')

for NIC in ${NICS}; do
	MAC=`xxd -l 6 -p /dev/urandom | sed -e "s/.\{2\}/&\:/g" | head -c 17`
        ifconfig ${NIC} down
        /usr/bin/macchanger -m ${MAC} ${NIC} 
        /bin/sleep 1
done

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script randmac "
    ;;
  stop)
    echo "Stopping script randmac"
    ;;
  *)
    echo "Usage: /etc/init.d/randmac {start|stop}"
    exit 1
    ;;
esac

exit 0
