#!/bin/sh

# stop local DNS resolver

echo -n "Stopping local DNS resolver..."
/etc/init.d/unbound stop && echo "done."

echo "Configuring iptables..."
# destinations you don't want routed through Tor
NON_TOR="192.168.0.0/16 172.16.0.0/18 10.0.0.0/8"

# the UID Tor runs as
TOR_UID="#TORPID#"

# Tor's TransPort
TRANS_PORT="9040"

iptables -F
iptables -t nat -F

iptables -A INPUT -i lo -j ACCEPT

## Established incoming connections are accepted.
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53
for NET in $NON_TOR 127.0.0.0/9 127.128.0.0/10; do
 iptables -t nat -A OUTPUT -d $NET -j RETURN
done
iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TRANS_PORT

iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
for NET in $NON_TOR 127.0.0.0/8; do
 iptables -A OUTPUT -d $NET -j ACCEPT
done
iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
iptables -A OUTPUT -j REJECT

echo "Configuring Tor..."

echo "DNSPort 53" >> /etc/tor/torrc
echo "TransPort 9040" >> /etc/tor/torrc

echo -n "Starting Tor..."
/etc/init.d/tor restart && echo "done."
zenity --info --text "Please wait for the TOR network to be established. This can take some time."

